import type { Metadata } from "next";
import "../globals.css";
import AppHeader from "@/components/common/AppHeader";
import Footer from "@/components/main/Footer";

export const metadata: Metadata = {
  title: "UUSJ My Page",
  description: "Generated by create next app",
};

export default function MyPageLayout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <AppHeader />
      {children}
      <Footer />
    </div>
  );
}
